# Generated by Django 3.0 on 2019-12-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice',
            new_name='noticeboard',
        ),
    ]
