# Generated by Django 3.0 on 2019-12-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191211_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='noticeboard',
            new_name='notice_board',
        ),
    ]
