# Generated by Django 3.0 on 2019-12-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191211_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club1', models.TextField()),
                ('club2', models.TextField()),
                ('club1score', models.CharField(max_length=2)),
                ('club2score', models.CharField(max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='notice_board',
            new_name='noticeboard',
        ),
    ]
